CREATE SCHEMA IF NOT EXISTS `projeto_01` DEFAULT CHARACTER SET utf8mb4 ;
USE `projeto_01` ;

CREATE TABLE IF NOT EXISTS `mydb`.`empresa` (
  `idempresa` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_emp` VARCHAR(100) NULL DEFAULT NULL,
  `cnpj_cpf` VARCHAR(45) NULL DEFAULT NULL,
  `razao_social` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `status_emp` VARCHAR(45) NULL DEFAULT NULL,
  `data_cadastro_emp` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idempresa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `projeto_01`.`tb_admin.online` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ip` VARCHAR(255) NOT NULL,
  `ultima_acao` DATETIME NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `projeto_01`.`tb_admin.usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `img` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `cargo` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `projeto_01`.`tb_admin.visitas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ip` VARCHAR(255) NOT NULL,
  `dia` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `projeto_01`.`tb_site.categorias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `order_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE IF NOT EXISTS `projeto_01`.`tb_site.config` (
  `titulo` VARCHAR(255) NOT NULL,
  `nome_autor` VARCHAR(255) NOT NULL,
  `descricao` TEXT NOT NULL,
  `icone1` VARCHAR(255) NOT NULL,
  `descricao1` TEXT NOT NULL,
  `icone2` VARCHAR(255) NOT NULL,
  `descricao2` TEXT NOT NULL,
  `icone3` VARCHAR(255) NOT NULL,
  `descricao3` TEXT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `projeto_01`.`tb_site.depoimentos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `depoimento` TEXT NOT NULL,
  `data` VARCHAR(255) NOT NULL,
  `order_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `projeto_01`.`tb_site.noticias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `categoria_id` INT(11) NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `conteudo` TEXT NOT NULL,
  `capa` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `order_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE IF NOT EXISTS `projeto_01`.`tb_site.servicos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `servico` TEXT NOT NULL,
  `order_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `projeto_01`.`tb_site.slides` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `slide` VARCHAR(255) NOT NULL,
  `order_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
